name: flutterfirebase
description: Test


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:  
  sdk: ">=2.12.0 <3.0.0" # dart
  flutter: 2.0.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0        
  firebase_core: "^1.0.1"
  firebase_auth: "^1.0.1"
  cloud_firestore: "^1.0.1"
  lint:
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.5
  equatable: ^2.0.0
  meta: ^1.3.0
  pedantic: ^1.11.0
  formz: ^0.4.0-nullsafety.0
  google_fonts: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  generate: true
